// <auto-generated />
using System;
using AuditCkDayo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditCkDayo.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260810150939_PcfReleaseAndAuditSettlement")]
    partial class PcfReleaseAndAuditSettlement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuditCkDayo.Models.AuditItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("AwaitingBranchVerification");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("AuditItems");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationNotes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AssignedEstablishmentId")
                        .HasColumnType("int");

                    b.Property<int>("AuditItemId")
                        .HasColumnType("int");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEstablishmentId");

                    b.HasIndex("AuditItemId");

                    b.HasIndex("CostCenterId");

                    b.ToTable("AuditItemDetails");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditItemId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuditItemId");

                    b.ToTable("AuditItemImages");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualChangeReturned")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ExpectedChange")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("PcfReleaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleManagerId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShortOverAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAcceptedExpenses")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalPCReleased")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PcfReleaseId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("ResponsibleManagerId");

                    b.ToTable("AuditSettlements");
                });

            modelBuilder.Entity("AuditCkDayo.Models.CashBreakdownLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Denomination")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SalesReportId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalesReportId");

                    b.ToTable("CashBreakdownLines");
                });

            modelBuilder.Entity("AuditCkDayo.Models.CashFlowEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RelatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TreasuryCashFlowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("TreasuryCashFlowId");

                    b.ToTable("CashFlowEntries");
                });

            modelBuilder.Entity("AuditCkDayo.Models.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("AuditCkDayo.Models.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OcrRawJson")
                        .HasColumnType("longtext");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("AuditCkDayo.Models.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMiscellaneous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOperatingBranch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("AuditCkDayo.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AuditCkDayo.Models.PcfRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("CashFlowEntryId")
                        .HasColumnType("int");

                    b.Property<int?>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReleasedByTreasuryUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CashFlowEntryId");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("ReleasedByTreasuryUserId");

                    b.ToTable("PcfReleases");
                });

            modelBuilder.Entity("AuditCkDayo.Models.PettyCashLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("AssociatedRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("CounterpartyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ResultingBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyUserId");

                    b.HasIndex("UserId");

                    b.ToTable("PettyCashLedgers");
                });

            modelBuilder.Entity("AuditCkDayo.Models.SalesReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BusinessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CashOut")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CashierName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CashierUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConfirmedCashToHandover")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("DocumentRecordId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("GCashAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("GrossSales")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("HandoverDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("OtherPaymentAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ReceiptNumberEnd")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReceiptNumberStart")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WitnessName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("DocumentRecordId");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("SalesReports");
                });

            modelBuilder.Entity("AuditCkDayo.Models.SurrenderRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ActionNotes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerNotes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("DeclaredAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("BuyerId");

                    b.ToTable("SurrenderRequests");
                });

            modelBuilder.Entity("AuditCkDayo.Models.TreasuryCashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CashFlowDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("NetCashFlow")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("StartingBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalCashIn")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalCashOut")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TreasuryUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreasuryUserId");

                    b.ToTable("TreasuryCashFlows");
                });

            modelBuilder.Entity("AuditCkDayo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyStartingFloat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTreasury")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PcfBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItem", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "Buyer")
                        .WithMany("AuditItems")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.Establishment", "Establishment")
                        .WithMany("AuditItems")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Buyer");

                    b.Navigation("Establishment");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItemDetail", b =>
                {
                    b.HasOne("AuditCkDayo.Models.Establishment", "AssignedEstablishment")
                        .WithMany()
                        .HasForeignKey("AssignedEstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.AuditItem", "AuditItem")
                        .WithMany("Details")
                        .HasForeignKey("AuditItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedEstablishment");

                    b.Navigation("AuditItem");

                    b.Navigation("CostCenter");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItemImage", b =>
                {
                    b.HasOne("AuditCkDayo.Models.AuditItem", "AuditItem")
                        .WithMany("Images")
                        .HasForeignKey("AuditItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditItem");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditSettlement", b =>
                {
                    b.HasOne("AuditCkDayo.Models.PcfRelease", "PcfRelease")
                        .WithMany()
                        .HasForeignKey("PcfReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "ResponsibleManager")
                        .WithMany()
                        .HasForeignKey("ResponsibleManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PcfRelease");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("ReceiverUser");

                    b.Navigation("ResponsibleManager");
                });

            modelBuilder.Entity("AuditCkDayo.Models.CashBreakdownLine", b =>
                {
                    b.HasOne("AuditCkDayo.Models.SalesReport", "SalesReport")
                        .WithMany("CashBreakdownLines")
                        .HasForeignKey("SalesReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SalesReport");
                });

            modelBuilder.Entity("AuditCkDayo.Models.CashFlowEntry", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.DocumentRecord", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.TreasuryCashFlow", "TreasuryCashFlow")
                        .WithMany("Entries")
                        .HasForeignKey("TreasuryCashFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("CostCenter");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Establishment");

                    b.Navigation("RelatedUser");

                    b.Navigation("SourceDocument");

                    b.Navigation("TreasuryCashFlow");
                });

            modelBuilder.Entity("AuditCkDayo.Models.DocumentRecord", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("AuditCkDayo.Models.Notification", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuditCkDayo.Models.PcfRelease", b =>
                {
                    b.HasOne("AuditCkDayo.Models.CashFlowEntry", "CashFlowEntry")
                        .WithMany()
                        .HasForeignKey("CashFlowEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "ReleasedByTreasuryUser")
                        .WithMany()
                        .HasForeignKey("ReleasedByTreasuryUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashFlowEntry");

                    b.Navigation("Establishment");

                    b.Navigation("ReceiverUser");

                    b.Navigation("ReleasedByTreasuryUser");
                });

            modelBuilder.Entity("AuditCkDayo.Models.PettyCashLedger", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "CounterpartyUser")
                        .WithMany()
                        .HasForeignKey("CounterpartyUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CounterpartyUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuditCkDayo.Models.SalesReport", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId");

                    b.HasOne("AuditCkDayo.Models.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId");

                    b.HasOne("AuditCkDayo.Models.DocumentRecord", "DocumentRecord")
                        .WithMany()
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditCkDayo.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashierUser");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("DocumentRecord");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("AuditCkDayo.Models.SurrenderRequest", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("AuditCkDayo.Models.TreasuryCashFlow", b =>
                {
                    b.HasOne("AuditCkDayo.Models.User", "TreasuryUser")
                        .WithMany()
                        .HasForeignKey("TreasuryUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TreasuryUser");
                });

            modelBuilder.Entity("AuditCkDayo.Models.User", b =>
                {
                    b.HasOne("AuditCkDayo.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditCkDayo.Models.User", "Manager")
                        .WithMany("StaffMembers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Establishment");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AuditCkDayo.Models.AuditItem", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("AuditCkDayo.Models.Establishment", b =>
                {
                    b.Navigation("AuditItems");
                });

            modelBuilder.Entity("AuditCkDayo.Models.SalesReport", b =>
                {
                    b.Navigation("CashBreakdownLines");
                });

            modelBuilder.Entity("AuditCkDayo.Models.TreasuryCashFlow", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AuditCkDayo.Models.User", b =>
                {
                    b.Navigation("AuditItems");

                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
